event: 2025 Colloquia in Combinatorics
edition: 18
date: 2025-05-07
locations:
  - QMUL
  - UCL
venues:
  - 'Events for the day will take place in the <a href="https://maps.app.goo.gl/tgigzvDrpn4iMmz19">Mathematical Sciences Building</a> on Mile End Road between Globe Road and Bancroft Road: talks in the Maths Lecture Theatre, coffee in the foyer.'
  - 'Events for the day will take place in <a href="https://maps.app.goo.gl/WeFXikXSujmCWN3z6">Bentham House</a> (UCL Laws) on the corner of Endsleigh Gardens and Endsleigh Street: talks in the Denys Holland Lecture Theatre, coffee and the poster session in the Hong Kong Seminar Room. Weather permitting, the reception will take place in the <a href="https://maps.app.goo.gl/5xpJ78ArJxDfztBt8">Japanese Gardens</a> behind the Student Centre.'

schedule:
  - time: "10:00"
    type: coffee
  - time: "10:30"
    type: talk
  - time: "11:20"
    type: talk
  - time: "12:10"
    type: lunch
  - time: "13:40"
    type: talk
  - time: "14:30"
    type: talk
  - time: "15:20"
    type: coffee
  - time: "15:50"
    type: talk
  - time: "16:40"
    type: talk
  - time: "17:45"
    type: reception

collections:
  talks:
    sort_by: number
  # tags:
  #   output: true
  #   permalink: tags/:path/

navigation:
  - name: Speakers
    link: 
  - name: Schedule
    link: /schedule.html
  - name: Registration
    link: https://onlinestore.ucl.ac.uk/conferences-and-events/faculty-of-mathematical-physical-sciences-c06/mathematics-f59/f59-2025-colloquia-in-combinatorics
  - name: Posters
    link: /posters.html
  - name: Funding
    link: /funding.html
  - name: Childcare
    link: /childcare.html
  - name: Code of Conduct
    link: /codeofconduct.html
  - name: Archive
    link: 

organisers:
  - name: Felix Fischer
    affiliation: QMUL
    link: https://webspace.maths.qmul.ac.uk/felix.fischer/
  - name: Shoham Letzter
    affiliation: UCL
    link: https://shohamlet.github.io/
  - name: Viresh Patel
    affiliation: QMUL
    link: https://sites.google.com/site/vireshspatel/
  - name: Alexey Pokrovskiy
    affiliation: UCL
    link: https://alexeypokrovskiy.com/
  - name: John Talbot
    affiliation: UCL
    link: https://www.ucl.ac.uk/quantum/people/dr-john-talbot

contacts:
  funding:
    name: John Talbot
    email: j.talbot@ucl.ac.uk
    subject: funding support
  posters:
    name: Shoham Letzter
    email: s.letzter@ucl.ac.uk
    subject: poster session

support:
  - name: British Combinatorial Committee
    link: https://www.britishcombinatorics.org.uk/
    logo: bcc.png
  - name: London Mathematical Society
    link: https://www.lms.ac.uk/
    logo: lms.png
  - name: Heilbronn Institute for Mathematical Research
    link: https://heilbronn.ac.uk/
    logo: himr.png
  - name: UKRI/EPSRC Additional Funding Programme for Mathematical Sciences
    logo: epsrc.png

## original settings from here

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown

mathjax: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: https://2dcic.github.io
domain: 2dcic.github.io

future: true
