event: 2025 Colloquia in Combinatorics
edition: 18
date: 2025-05-07
locations:
  - QMUL
  - UCL

collections:
  talks:
    sort_by: number
  # tags:
  #   output: true
  #   permalink: tags/:path/

navigation:
  - name: Speakers
    link: /speakers.html
  - name: Schedule
    link: 
  - name: Registration
    link: https://onlinestore.ucl.ac.uk/conferences-and-events/faculty-of-mathematical-physical-sciences-c06/mathematics-f59
  - name: Posters
    link: 
  - name: Funding
    link: 
  - name: Childcare
    link: 
  - name: Code of Conduct
    link: /codeofconduct.html
  - name: Archive
    link: 

organisers:
  - name: Felix Fischer
    affiliation: QMUL
    link: https://webspace.maths.qmul.ac.uk/felix.fischer/
  - name: Shoham Letzter
    affiliation: UCL
    link: https://shohamlet.github.io/
  - name: Viresh Patel
    affiliation: QMUL
    link: https://sites.google.com/site/vireshspatel/
  - name: Alexey Pokrovskiy
    affiliation: UCL
    link: https://alexeypokrovskiy.com/
  - name: John Talbot
    affiliation: UCL
    link: https://www.ucl.ac.uk/quantum/people/dr-john-talbot

support:
  - name: London Mathematical Society
    link: https://www.lms.ac.uk/
    logo: lms.png
  - name: Heilbronn Institute for Mathematical Research
    link: https://heilbronn.ac.uk/
    logo: himr.png
  - name: UKRI/EPSRC Additional Funding Programme for Mathematical Sciences
    logo: epsrc.png

## original settings from here

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

url: https://2dcic.github.io
domain: 2dcic.github.io

future: true
